fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
#redefinition des routes FOSUser personnalisées  
fos_user_registration_confirm: 
    path: /register/confirm/{token}
    defaults: { _controller: innoLCLAllUserBundle:Registration:confirm }  
    
fos_user_registration_confirmed: 
    path: /register/confirmed
    defaults: { _controller: innoLCLfrontBundle:Default:confirmed }  




# Route de connexion au FrontOffice
fos_user_security_login:
    path: /
    defaults: { _controller: innoLCLfrontBundle:Default:index }

# Route de vérification de connexion au FrontOffice
fos_user_security_check:
    path: /check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

# Route de déconnexion du FrontOffice
fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

# Affichage formulaire étape 1 recup mdp : 'indiquer votre mail'
innoLCL_alluserbundle_resetting_request:
    path: /resetting/request_pwd
    defaults: { _controller: innoLCLAllUserBundle:Resetting:request }

# Affichage formulaire étape 2 gestion formulaire pour envoi du lien de recup par mail
innoLCL_alluserbundle_resetting_send_email:
    path:  /resetting/send-email
    defaults: { _controller: innoLCLAllUserBundle:Resetting:sendEmail }
    requirements:
        _method: POST

# Affichage page étape 3 : entrer nouveau mot de passe
fos_user_resetting_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: innoLCLAllUserBundle:Resetting:reset }
    requirements:
        _method: GET|POST



# Route de redirection après le check
innoLCL_alluserbundle_redirect:
    path:  /redirectUser
    defaults: { _controller: innoLCLAllUserBundle:Redirect:ByRoleRedirection }




# Route de connexion au Backoffice
fos_admin_user_security_login:
    path:  /admin/
    defaults: { _controller: innoLCLAllUserBundle:Adminlog:login }

# Route de vérification de connexion au Backoffice
fos_admin_user_security_check:
    path:  /admincheck
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

# Route de déconnexion du Backoffice
fos_admin_user_security_logout:
    path:  /admin/logout
    defaults: { _controller: innoLCLAllUserBundle:Adminlog:logout }
    
#mainteneur de session active ajax
session_check:
    path:  /session_check
    defaults: { _controller: innoLCLAllUserBundle:Session:check }
    requirements:
        _method: POST
